### ISSUE TITLE
Determine what we can leverage for CivitasDX.com

### ISSUE THREAD

**Issue by bderfer68** [agilesix/AgileSix.com#19]
We need a website for our new JV CivitasDX. I'm hoping that we can reuse parts of our AgileSix website as a starting point. 

What we need is an analysis of what we can leverage and any notes around overall approach to reuse,  risks, etc. This can be written up as notes in this user story, or linked to a separate spreadsheet if that conveys the information better.

Ex: Do we want to leverage the same theme, or start with a Gatsby starter theme?

AC: 
 - A spreadsheet representing the analysis similar to what is described above has been added to this story.

**Comment by ElijahLynn** [comment]
Per our Zoom, we discussed no big need to depart from the stack we are using now which is Netlify CMS + a Gatsby JS theme/template. This keeps things super simple because there is no real-time database and the database is actually *.md files in the GH repo. 

Next steps I am thinking of are, a single Epic:

1.  New GitHub ORG and Repo (public, #opensource) setup
1.  ZenHub setup
1.  Use Gatsby starter theme, don't re-use Agile6's code. Can use for reference though. 
1.  Netlify account creation and setup
1.  Netlify CI/preview environments setup
1.  Setup DNS to point to Netlify

This will get us setup to start developing rapidly with PR review environments.

**Comment by JQuaggles** [comment]
@bderfer68 We can probably close this
