### ISSUE TITLE
Add Careers Page

### ISSUE THREAD

**Issue by bderfer68** [agilesix/AgileSix.com#30]
As a potential hiring candidate for Agile Six I would like to know what positions are available and how to apply for open positions.

**Comment by DanielMiller-agile6** [comment]
I posted a branch and PR with a skeleton for the new careers page, and setup the netlify-cms admin to post changes against my branch.  We can use the PR preview page so that others can provide content changes via admin interface and/or start discussion on additional changes we'd like to make.

https://deploy-preview-31--agile6.netlify.app

https://deploy-preview-31--agile6.netlify.app/admin

**Comment by DanielMiller-agile6** [comment]
I worked with @JQuaggles  on this and the new careers page is now live.

We'll do a follow-up CMS change to the `/teams` page to reduce some redundant content.

I'll also take a look at improving the job board.  We're currently just linking to the GH job board page (like before from the teams page).  II tried the iframe embed approach ([#2 GH integration options](https://agile6.greenhouse.io/configure/dev_center/integration)) but this proved difficult with our SPA setup, and didn't really provide a nice UX anyhow.  I'll look into a direct APIi integration approach ([#3 on integration options](https://agile6.greenhouse.io/configure/dev_center/integration)) when I have some time, which should provide a nicer experience.

**Comment by JQuaggles** [comment]
This was rolled out.
